# Generated by Django 4.2.2 on 2023-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_images/'),
        ),
    ]
